### ISSUE TITLE
Add minimum Ruby version required to gemspec

### ISSUE THREAD

**Issue by Ruenzuo** [xing/XNGPodsSynchronizer#10]
Attempting to use XNGPodsSynchronizer with Ruby 2.0 (default macOS version) results in:

```
4demcrisosto:pods-synchronizer crisosto$ ./sync 
/Users/crisosto/HERE/Samples/XNGPodsSynchronizer/lib/updater.rb:1:in `require': /Users/crisosto/HERE/Samples/XNGPodsSynchronizer/lib/updater/pod.rb:4: syntax error, unexpected ')' (SyntaxError)
/Users/crisosto/HERE/Samples/XNGPodsSynchronizer/lib/updater/pod.rb:27: syntax error, unexpected keyword_end, expecting end-of-input
	from /Users/crisosto/HERE/Samples/XNGPodsSynchronizer/lib/updater.rb:1:in `<top (required)>'
	from /Users/crisosto/HERE/Samples/XNGPodsSynchronizer/bin/pod-synchronize:10:in `require'
	from /Users/crisosto/HERE/Samples/XNGPodsSynchronizer/bin/pod-synchronize:10:in `<top (required)>'
	from /Users/crisosto/.rvm/gems/ruby-2.0.0-p648/bin/pod-synchronize:23:in `load'
	from /Users/crisosto/.rvm/gems/ruby-2.0.0-p648/bin/pod-synchronize:23:in `<main>'
	from /Users/crisosto/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /Users/crisosto/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
```

2.4 (latest available) works just fine, 2.3 as well (AFAIR, the one we used at XING). So apparently we're using some language features not available in 2.0 here: [pod.rb](https://github.com/xing/XNGPodsSynchronizer/blob/master/lib/updater/pod.rb), but I can't identify what is it, maybe the conditional assignment?

We should add something like this: [`required_ruby_version `](https://github.com/CocoaPods/CocoaPods/blob/master/cocoapods.gemspec#L59).

@pietbrauer @q231950 any ideas?

**Comment by pietbrauer** [comment]
My guess would be the parameter label, have you tried removing that? Although this is a 2.0 feature so I really don't know.

**Comment by matthias-maennich** [comment]
https://robots.thoughtbot.com/ruby-2-keyword-arguments#required-keyword-arguments
So yea, a required ruby version should be added to at least `2.1`.

**Comment by Ruenzuo** [comment]
Awesome, happy to submit a fix for this 💖

**Comment by pietbrauer** [comment]
Shouldn't we remove the label and work with the system ruby like Cocoapods does it?

**Comment by Ruenzuo** [comment]
Do you know what's the default Ruby version used in CircleCI/Travis containers? We should definitively use that one.

**Comment by Ruenzuo** [comment]
It uses a [2.3](https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-105/index.html). Honestly I'd be happy using a newer Ruby version as long as it's correctly specified in the Gemspec. CocoaPods is something you run in a developer's computer, this gem is something you run on CI. Given that the best provider uses an up-to-date Ruby version, we shouldn't hold back imo 😄

**Comment by pietbrauer** [comment]
Sierra ships with [2.0.0p648](https://apple.stackexchange.com/a/257629) as most people will use this on a macOS CI machine I think we should use that version of ruby too and make sure our CI for the tests is correctly set to the old version as well.

**Comment by Ruenzuo** [comment]
I think while setting up a CI system you always want to have control over everything, including runtimes, not defaulting to what's available in the platform. Using the latest versions (or patch-sets) gives you "bug fixes and performance improvements ™" which is always good for a CI system.

That being said, I honestly don't mind stop using 2.1 features and set 2.0 as required version. That's probably going to make the life easier for everyone.
